### PR TITLE
Matlab makefile

### PR DESCRIPTION
**Pull request by otbrown**
- Added a closing parenthesis to the second assert statement in the Matlab command.
- Added `nohup <MATLAB snipped> && wait` to avoid Matlab printing to stdout instead of `test.log`
- Added check to see if `test.log` exists and is not empty before grepping for assertion failures

My apologies, should have made separate commits for the missing bracket and the redirection stuff... Issue was that Matlab would not begin printing to stdout until it had completed and exited, by which time the (empty) test.log had been created and grepped.

### CODE REVIEW

**Comment by eromero-vlc** [comment]
Thanks for the contribution. The MATLAB test was poorly designed: it passes even with errors in the script. I should fix it.

I've been testing MATLAB R2015 and newer versions in Linux and MacOS and nohup matlab ... && wait never ends. In my case the command line 'matlab' doesn't produce any child so the bash script waits forever. What matlab are you using and in which platform?

**Comment by otbrown** [comment]
You're welcome, thanks for the robust alternative to eigs!

It occurred to me after I'd submitted the PR that it might be an overly local solution -- I'm using R2016a on Ubuntu 14.04 LTS, and R2016a on CentOS 7.2.1511. Both pass through the script with no problems. Could be a Matlab version difference?

**Comment by eromero-vlc** [comment]
Can you try with nohup, using matlab logfile and without && wait? Something like this:
 
nohup $(MATLAB) -nodesktop -nodisplay -r "A=diag(1:50);E=primme_eigs(A,6);assert(norm(E-(50:-1:45)')<1e-9);E=primme_eigs(@(x)A*x,50,6);assert(norm(E-(50:-1:45)')<1e-9);disp(['Suc' 'cess']);exit" -logfile test.log > /dev/null

**Comment by otbrown** [comment]
Can confirm that works as expected on both my platforms.

**Comment by eromero-vlc** [comment]
Excellent! We appreciate these runs on other machines. I'll commit this together with your changes into master.

**Comment by otbrown** [comment]
Glad to help!

**Pull request merged**
