### PR TITLE
Fixed f90 compilation issue

### PR DESCRIPTION
**Pull request by IgorGayday**
Fixes primme/primme#32

### CODE REVIEW

**Comment by eromero-vlc** [comment]
I am getting this error with gfortran 9.2:

> $ make ex_eigs_dseqf90 
> gfortran -fno-second-underscore -O -I../include  -c ex_eigs_dseqf90.f90 -o ex_eigs_dseqf90.o
ex_eigs_dseqf90.f90:82:10:
>
>   82 |    ierr = primme_set_member(primme, PRIMME_matrixMatvec, MV)
>      |          1
> Error: There is no specific function for the generic ‘primme_set_member’ at (1)

Do you have this error?

**Comment by dartlenin** [comment]
No, I did not have that error, I didn't try gfortran, only ifort. I think the new commit should fix it.

**Comment by eromero-vlc** [comment]
Thanks for the PR! It is already on master. I have modified things to make it work with gfortran. Instead of:
```
ierr = primme_set_member(primme, PRIMME_matrixMatvec, MV)
```
for now one has to match the function name with the type:
```
ierr = primme_set_member_matvec_double(primme, PRIMME_matrixMatvec, MV)
```
Hopefully they are going to be temporal. See commit 97cbc23.

**Comment by dartlenin** [comment]
FC variable already has a default value `f77` so `gfortran` is not assigned via `?=` operator, at least on my machine.

Also, an alternative way to match the declared interfaces would be through the procedure pointers:
```
procedure, pointer :: MV_ptr
MV_ptr => MV
ierr = primme_set_member(primme, PRIMME_matrixMatvec, MV_ptr)
```
I think this way should work with gfortran.

**Comment by dartlenin** [comment]
Also, this does not compile with `ifort`. See [error_log](https://github.com/primme/primme/files/4371452/error_log.txt)

**Comment by eromero-vlc** [comment]
Fixed on commit a37163d! Thanks for reporting them!

**Pull request closed without merging**
