### PR TITLE
Make build work on Mac and with MKL

### PR DESCRIPTION
**Pull request by andreasnoack**
I'm not a Makefile master so this might not be the right way to do it. However, it makes things work on my Mac.

Btw, thanks for the package. I'm pretty enthusiastic about it and have started wrapping it in Julia. Will push to https://github.com/andreasnoack/Primme.jl later today when the build process is working.

### CODE REVIEW

**Comment by eromero-vlc** [comment]
Thank you for your contribution. I've already put your changes on master. I changed a little bit how libprimme.dylib is generated. Can you check if that works for you?

**Comment by andreasnoack** [comment]
Great. I just tried it out and is seems to work fine.

**Comment by andreasnoack** [comment]
Btw. Do you have any idea what is causing this error https://travis-ci.org/andreasnoack/Primme.jl#L290

**Comment by eromero-vlc** [comment]
It is a bug in the makefiles when compiling in parallel. For now you can avoid that by replacing "make -j solib" with "make -C src auto_headers; make -j solib" in deps/build.jl.

**Pull request merged**
